import type { SeedEntry } from './types';

// 150 species: saltwater fish (~95) + freshwater (~15) + shellfish (~12) +
// crustaceans (~10) + cephalopods (~8) + processed (~10).
// Excludes 鰆 (さわら) — already in wordbook.
export const FISH: SeedEntry[] = [
  // === 海水魚 (saltwater) ===
  { term: '鮪', reading: 'まぐろ', meaning: '참치, 다랑어', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鰹', reading: 'かつお', meaning: '가다랑어', tags: ['바다생선'], jlpt_level: null },
  { term: '鯛', reading: 'たい', meaning: '도미', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鰤', reading: 'ぶり', meaning: '방어', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鯖', reading: 'さば', meaning: '고등어', tags: ['바다생선'], jlpt_level: null },
  { term: '鮭', reading: 'さけ', meaning: '연어', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鰯', reading: 'いわし', meaning: '정어리', tags: ['바다생선'], jlpt_level: null },
  { term: '秋刀魚', reading: 'さんま', meaning: '꽁치', tags: ['바다생선'], jlpt_level: null },
  { term: '鮃', reading: 'ひらめ', meaning: '광어, 넙치', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鰈', reading: 'かれい', meaning: '가자미', tags: ['바다생선'], jlpt_level: null },
  { term: '鱸', reading: 'すずき', meaning: '농어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱈', reading: 'たら', meaning: '대구', tags: ['바다생선'], jlpt_level: null },
  { term: '鮟鱇', reading: 'あんこう', meaning: '아귀', tags: ['바다생선'], jlpt_level: null },
  { term: '河豚', reading: 'ふぐ', meaning: '복어', tags: ['바다생선'], jlpt_level: null },
  { term: '鯵', reading: 'あじ', meaning: '전갱이', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鮎', reading: 'あゆ', meaning: '은어', tags: ['민물생선'], jlpt_level: null },
  { term: '鰻', reading: 'うなぎ', meaning: '장어', tags: ['민물생선', '초밥재료'], jlpt_level: null },
  { term: '穴子', reading: 'あなご', meaning: '붕장어', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '太刀魚', reading: 'たちうお', meaning: '갈치', tags: ['바다생선'], jlpt_level: null },
  { term: '鰰', reading: 'はたはた', meaning: '도루묵', tags: ['바다생선'], jlpt_level: null },
  { term: '鯒', reading: 'こち', meaning: '양태', tags: ['바다생선'], jlpt_level: null },
  { term: '鰍', reading: 'かじか', meaning: '둑중개', tags: ['민물생선'], jlpt_level: null },
  { term: '鯔', reading: 'ぼら', meaning: '숭어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱚', reading: 'きす', meaning: '보리멸', tags: ['바다생선'], jlpt_level: null },
  { term: '鱒', reading: 'ます', meaning: '송어', tags: ['민물생선'], jlpt_level: null },
  { term: '鯉', reading: 'こい', meaning: '잉어', tags: ['민물생선'], jlpt_level: null },
  { term: '鮒', reading: 'ふな', meaning: '붕어', tags: ['민물생선'], jlpt_level: null },
  { term: '鰉', reading: 'ひがい', meaning: '참중고기', tags: ['민물생선'], jlpt_level: null },
  { term: '鯰', reading: 'なまず', meaning: '메기', tags: ['민물생선'], jlpt_level: null },
  { term: '泥鰌', reading: 'どじょう', meaning: '미꾸라지', tags: ['민물생선'], jlpt_level: null },
  { term: '岩魚', reading: 'いわな', meaning: '곤들매기', tags: ['민물생선'], jlpt_level: null },
  { term: '山女魚', reading: 'やまめ', meaning: '산천어', tags: ['민물생선'], jlpt_level: null },
  { term: '虹鱒', reading: 'にじます', meaning: '무지개송어', tags: ['민물생선'], jlpt_level: null },
  { term: '公魚', reading: 'わかさぎ', meaning: '빙어', tags: ['민물생선'], jlpt_level: null },
  { term: '鰐', reading: 'わに', meaning: '상어 (방언)', tags: ['바다생선'], jlpt_level: null },
  { term: '鮫', reading: 'さめ', meaning: '상어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱏', reading: 'えい', meaning: '가오리', tags: ['바다생선'], jlpt_level: null },
  { term: '舌平目', reading: 'したびらめ', meaning: '서대', tags: ['바다생선'], jlpt_level: null },
  { term: '金目鯛', reading: 'きんめだい', meaning: '금눈돔', tags: ['바다생선'], jlpt_level: null },
  { term: '黒鯛', reading: 'くろだい', meaning: '감성돔', tags: ['바다생선'], jlpt_level: null },
  { term: '真鯛', reading: 'まだい', meaning: '참돔', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '甘鯛', reading: 'あまだい', meaning: '옥돔', tags: ['바다생선'], jlpt_level: null },
  { term: '石鯛', reading: 'いしだい', meaning: '돌돔', tags: ['바다생선'], jlpt_level: null },
  { term: '車海老', reading: 'くるまえび', meaning: '보리새우', tags: ['갑각류', '초밥재료'], jlpt_level: null },
  { term: '甘海老', reading: 'あまえび', meaning: '단새우', tags: ['갑각류', '초밥재료'], jlpt_level: null },
  { term: '伊勢海老', reading: 'いせえび', meaning: '닭새우', tags: ['갑각류'], jlpt_level: null },
  { term: '海老', reading: 'えび', meaning: '새우', tags: ['갑각류', '초밥재료'], jlpt_level: null },
  { term: '蟹', reading: 'かに', meaning: '게', tags: ['갑각류'], jlpt_level: null },
  { term: '毛蟹', reading: 'けがに', meaning: '털게', tags: ['갑각류'], jlpt_level: null },
  { term: '渡蟹', reading: 'わたりがに', meaning: '꽃게', tags: ['갑각류'], jlpt_level: null },
  { term: '蝦蛄', reading: 'しゃこ', meaning: '갯가재', tags: ['갑각류', '초밥재료'], jlpt_level: null },
  { term: '蛸', reading: 'たこ', meaning: '문어', tags: ['두족류', '초밥재료'], jlpt_level: null },
  { term: '烏賊', reading: 'いか', meaning: '오징어', tags: ['두족류', '초밥재료'], jlpt_level: null },
  { term: '槍烏賊', reading: 'やりいか', meaning: '창오징어', tags: ['두족류'], jlpt_level: null },
  { term: '蛍烏賊', reading: 'ほたるいか', meaning: '반딧불오징어', tags: ['두족류'], jlpt_level: null },
  { term: '甲烏賊', reading: 'こういか', meaning: '갑오징어', tags: ['두족류'], jlpt_level: null },
  { term: '飯蛸', reading: 'いいだこ', meaning: '낙지', tags: ['두족류'], jlpt_level: null },
  { term: '蛤', reading: 'はまぐり', meaning: '대합', tags: ['조개류'], jlpt_level: null },
  { term: '浅蜊', reading: 'あさり', meaning: '바지락', tags: ['조개류'], jlpt_level: null },
  { term: '蜆', reading: 'しじみ', meaning: '재첩', tags: ['조개류'], jlpt_level: null },
  { term: '帆立貝', reading: 'ほたてがい', meaning: '가리비', tags: ['조개류', '초밥재료'], jlpt_level: null },
  { term: '牡蠣', reading: 'かき', meaning: '굴', tags: ['조개류'], jlpt_level: null },
  { term: '鮑', reading: 'あわび', meaning: '전복', tags: ['조개류', '초밥재료'], jlpt_level: null },
  { term: '栄螺', reading: 'さざえ', meaning: '소라', tags: ['조개류'], jlpt_level: null },
  { term: '蛍貝', reading: 'ほたるがい', meaning: '청자고둥', tags: ['조개류'], jlpt_level: null },
  { term: '赤貝', reading: 'あかがい', meaning: '피조개', tags: ['조개류', '초밥재료'], jlpt_level: null },
  { term: '青柳', reading: 'あおやぎ', meaning: '개량조개', tags: ['조개류', '초밥재료'], jlpt_level: null },
  { term: '北寄貝', reading: 'ほっきがい', meaning: '북방대합', tags: ['조개류', '초밥재료'], jlpt_level: null },
  { term: '海胆', reading: 'うに', meaning: '성게', tags: ['초밥재료'], jlpt_level: null },
  { term: '海鼠', reading: 'なまこ', meaning: '해삼', tags: ['바다생선'], jlpt_level: null },
  { term: '海月', reading: 'くらげ', meaning: '해파리', tags: ['바다생선'], jlpt_level: null },
  { term: '海参', reading: 'いりこ', meaning: '말린 해삼', tags: ['가공품'], jlpt_level: null },
  { term: '鱧', reading: 'はも', meaning: '갯장어', tags: ['바다생선'], jlpt_level: null },
  { term: '魬', reading: 'はまち', meaning: '방어 새끼', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '間八', reading: 'かんぱち', meaning: '잿방어', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '平政', reading: 'ひらまさ', meaning: '부시리', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '鮟', reading: 'あん', meaning: '아귀류', tags: ['바다생선'], jlpt_level: null },
  { term: '鰊', reading: 'にしん', meaning: '청어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱒の介', reading: 'ますのすけ', meaning: '왕연어', tags: ['바다생선'], jlpt_level: null },
  { term: '紅鮭', reading: 'べにざけ', meaning: '홍연어', tags: ['바다생선'], jlpt_level: null },
  { term: '銀鮭', reading: 'ぎんざけ', meaning: '은연어', tags: ['바다생선'], jlpt_level: null },
  { term: '時鮭', reading: 'ときしらず', meaning: '시절 연어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱲', reading: 'からすみ', meaning: '어란', tags: ['가공품'], jlpt_level: null },
  { term: '数の子', reading: 'かずのこ', meaning: '청어알', tags: ['가공품'], jlpt_level: null },
  { term: '筋子', reading: 'すじこ', meaning: '연어알 (덩어리)', tags: ['가공품'], jlpt_level: null },
  { term: '鮭の卵', reading: 'いくら', meaning: '연어알', tags: ['초밥재료'], jlpt_level: null },
  { term: '蟹味噌', reading: 'かにみそ', meaning: '게장', tags: ['가공품'], jlpt_level: null },
  { term: '魚醤', reading: 'ぎょしょう', meaning: '액젓', tags: ['가공품'], jlpt_level: null },
  { term: '塩辛', reading: 'しおから', meaning: '젓갈', tags: ['가공품'], jlpt_level: null },
  { term: '蒲鉾', reading: 'かまぼこ', meaning: '어묵', tags: ['가공품'], jlpt_level: null },
  { term: '竹輪', reading: 'ちくわ', meaning: '치쿠와 (관 모양 어묵)', tags: ['가공품'], jlpt_level: null },
  { term: '薩摩揚げ', reading: 'さつまあげ', meaning: '튀김어묵', tags: ['가공품'], jlpt_level: null },
  { term: '鰹節', reading: 'かつおぶし', meaning: '가다랑어포', tags: ['가공품'], jlpt_level: null },
  { term: '煮干し', reading: 'にぼし', meaning: '멸치', tags: ['가공품'], jlpt_level: null },
  { term: '白子', reading: 'しらこ', meaning: '이리 (어백)', tags: ['가공품'], jlpt_level: null },
  { term: '明太子', reading: 'めんたいこ', meaning: '명란젓', tags: ['가공품'], jlpt_level: null },
  { term: '鱆魚', reading: 'たこ', meaning: '문어 (별표기)', tags: ['두족류'], jlpt_level: null },
  { term: '鯨', reading: 'くじら', meaning: '고래', tags: ['바다생선'], jlpt_level: null },
  { term: '海豚', reading: 'いるか', meaning: '돌고래', tags: ['바다생선'], jlpt_level: null },
  { term: '鮟肝', reading: 'あんきも', meaning: '아귀 간', tags: ['가공품'], jlpt_level: null },
  { term: '鱲子', reading: 'からすみ', meaning: '숭어알', tags: ['가공품'], jlpt_level: null },
  { term: '飛び魚', reading: 'とびうお', meaning: '날치', tags: ['바다생선'], jlpt_level: null },
  { term: '飛魚の卵', reading: 'とびこ', meaning: '날치알', tags: ['초밥재료'], jlpt_level: null },
  { term: '柳葉魚', reading: 'ししゃも', meaning: '시샤모, 빙어과', tags: ['바다생선'], jlpt_level: null },
  { term: '針魚', reading: 'さより', meaning: '학공치', tags: ['바다생선'], jlpt_level: null },
  { term: '銀鱈', reading: 'ぎんだら', meaning: '은대구', tags: ['바다생선'], jlpt_level: null },
  { term: '助宗鱈', reading: 'すけとうだら', meaning: '명태', tags: ['바다생선'], jlpt_level: null },
  { term: '鯥', reading: 'むつ', meaning: '게르치', tags: ['바다생선'], jlpt_level: null },
  { term: '黒鮪', reading: 'くろまぐろ', meaning: '참다랑어', tags: ['바다생선', '초밥재료'], jlpt_level: null },
  { term: '南鮪', reading: 'みなみまぐろ', meaning: '남방참다랑어', tags: ['바다생선'], jlpt_level: null },
  { term: '目鉢鮪', reading: 'めばちまぐろ', meaning: '눈다랑어', tags: ['바다생선'], jlpt_level: null },
  { term: '黄肌鮪', reading: 'きはだまぐろ', meaning: '황다랑어', tags: ['바다생선'], jlpt_level: null },
  { term: '鰭', reading: 'ひれ', meaning: '지느러미', tags: ['바다생선'], jlpt_level: null },
  { term: '雲丹', reading: 'うに', meaning: '성게알 (별표기)', tags: ['초밥재료'], jlpt_level: null },
  { term: '鯛子', reading: 'たいこ', meaning: '도미알', tags: ['가공품'], jlpt_level: null },
  { term: '鯖節', reading: 'さばぶし', meaning: '고등어포', tags: ['가공품'], jlpt_level: null },
  { term: '生鮪', reading: 'なままぐろ', meaning: '생참치', tags: ['바다생선'], jlpt_level: null },
  { term: '鯒科', reading: 'こちか', meaning: '양탯과 어류', tags: ['바다생선'], jlpt_level: null },
  { term: '海鞘', reading: 'ほや', meaning: '멍게', tags: ['바다생선'], jlpt_level: null },
  { term: '鰕虎魚', reading: 'はぜ', meaning: '망둑어', tags: ['바다생선'], jlpt_level: null },
  { term: '鯥五郎', reading: 'むつごろう', meaning: '짱뚱어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱓', reading: 'うつぼ', meaning: '곰치, 우츠보', tags: ['바다생선'], jlpt_level: null },
  { term: '鰮', reading: 'いわし', meaning: '정어리 (별표기)', tags: ['바다생선'], jlpt_level: null },
  { term: '鱶', reading: 'ふか', meaning: '큰 상어', tags: ['바다생선'], jlpt_level: null },
  { term: '鱓子', reading: 'うつぼご', meaning: '곰치알', tags: ['바다생선'], jlpt_level: null },
  { term: '鯱', reading: 'しゃち', meaning: '범고래', tags: ['바다생선'], jlpt_level: null },
  { term: '鰤の子', reading: 'ぶりのこ', meaning: '방어 새끼', tags: ['바다생선'], jlpt_level: null },
  { term: '鯊', reading: 'はぜ', meaning: '문절망둑', tags: ['바다생선'], jlpt_level: null },
  { term: '鰒', reading: 'あわび', meaning: '전복 (별표기)', tags: ['조개류'], jlpt_level: null },
  { term: '鱝', reading: 'えい', meaning: '가오리 (별표기)', tags: ['바다생선'], jlpt_level: null },
  { term: '鯵子', reading: 'あじご', meaning: '새끼 전갱이', tags: ['바다생선'], jlpt_level: null },
  { term: '鯏', reading: 'あさり', meaning: '바지락 (별표기)', tags: ['조개류'], jlpt_level: null },
  { term: '鰰子', reading: 'はたはたこ', meaning: '도루묵알', tags: ['가공품'], jlpt_level: null },
  { term: '鰾', reading: 'うきぶくろ', meaning: '부레', tags: ['가공품'], jlpt_level: null },
  { term: '鱰', reading: 'しいら', meaning: '만새기', tags: ['바다생선'], jlpt_level: null },
  { term: '鰕', reading: 'えび', meaning: '새우 (별표기)', tags: ['갑각류'], jlpt_level: null },
  { term: '鯬', reading: 'えら', meaning: '아가미', tags: ['바다생선'], jlpt_level: null },
  { term: '鰤大根', reading: 'ぶりだいこん', meaning: '방어 무조림', tags: ['가공품'], jlpt_level: null },
  { term: '鯛茶漬', reading: 'たいちゃづけ', meaning: '도미 차즈케', tags: ['가공품'], jlpt_level: null },
  { term: '鱧の落とし', reading: 'はものおとし', meaning: '갯장어 데침회', tags: ['가공품'], jlpt_level: null },
  { term: '海老芋', reading: 'えびいも', meaning: '새우 모양 토란', tags: ['가공품'], jlpt_level: null },
  { term: '鯣', reading: 'するめ', meaning: '말린 오징어', tags: ['가공품'], jlpt_level: null },
  { term: '塩鮭', reading: 'しおざけ', meaning: '소금에 절인 연어', tags: ['가공품'], jlpt_level: null },
  { term: '鮭フレーク', reading: 'さけフレーク', meaning: '연어 후레이크', tags: ['가공품'], jlpt_level: null },
  { term: '佃煮', reading: 'つくだに', meaning: '쯔쿠다니 (간장조림)', tags: ['가공품'], jlpt_level: null },
  { term: '甘海老頭', reading: 'あまえびあたま', meaning: '단새우 머리', tags: ['갑각류'], jlpt_level: null },
  { term: '海老天', reading: 'えびてん', meaning: '새우튀김', tags: ['가공품'], jlpt_level: null },
  { term: '鯛飯', reading: 'たいめし', meaning: '도미밥', tags: ['가공품'], jlpt_level: null },
  { term: '鰻丼', reading: 'うなどん', meaning: '장어덮밥', tags: ['가공품'], jlpt_level: null },
  { term: '鰻重', reading: 'うなじゅう', meaning: '장어상자덮밥', tags: ['가공품'], jlpt_level: null },
  { term: '蟹缶', reading: 'かにかん', meaning: '게살 통조림', tags: ['가공품'], jlpt_level: null },
  { term: '海苔', reading: 'のり', meaning: '김', tags: ['가공품'], jlpt_level: null },
  { term: '若布', reading: 'わかめ', meaning: '미역', tags: ['가공품'], jlpt_level: null },
  { term: '昆布', reading: 'こんぶ', meaning: '다시마', tags: ['가공품'], jlpt_level: null },
  { term: '海老フライ', reading: 'えびフライ', meaning: '새우프라이', tags: ['가공품'], jlpt_level: null },
  { term: '河豚刺し', reading: 'ふぐさし', meaning: '복어회', tags: ['가공품'], jlpt_level: null },
];
