import type { SeedEntry } from './types';

// 300 ingredient entries. Excludes 滑子 (なめこ) — already in wordbook.
export const INGREDIENTS: SeedEntry[] = [
  // === 잎채소 (leafy vegetables) ===
  { term: 'キャベツ', reading: 'キャベツ', meaning: '양배추', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '白菜', reading: 'はくさい', meaning: '배추', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'ほうれん草', reading: 'ほうれんそう', meaning: '시금치', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '小松菜', reading: 'こまつな', meaning: '소송채', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'レタス', reading: 'レタス', meaning: '양상추', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'サニーレタス', reading: 'サニーレタス', meaning: '꽃상추', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'サンチュ', reading: 'サンチュ', meaning: '상추', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '春菊', reading: 'しゅんぎく', meaning: '쑥갓', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '水菜', reading: 'みずな', meaning: '미즈나, 경수채', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '青梗菜', reading: 'チンゲンサイ', meaning: '청경채', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'ニラ', reading: 'ニラ', meaning: '부추', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '長葱', reading: 'ながねぎ', meaning: '대파', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '青葱', reading: 'あおねぎ', meaning: '쪽파', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '万能葱', reading: 'ばんのうねぎ', meaning: '실파', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '紫蘇', reading: 'しそ', meaning: '차조기', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '大葉', reading: 'おおば', meaning: '깻잎 (자소엽)', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'パセリ', reading: 'パセリ', meaning: '파슬리', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'バジル', reading: 'バジル', meaning: '바질', tags: ['채소', '향신료'], jlpt_level: null },
  { term: 'ルッコラ', reading: 'ルッコラ', meaning: '루꼴라', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'クレソン', reading: 'クレソン', meaning: '크레송, 물냉이', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: 'モロヘイヤ', reading: 'モロヘイヤ', meaning: '몰로키아', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '芽キャベツ', reading: 'めキャベツ', meaning: '방울양배추', tags: ['채소', '잎채소'], jlpt_level: null },

  // === 뿌리채소 (root vegetables) ===
  { term: '人参', reading: 'にんじん', meaning: '당근', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '大根', reading: 'だいこん', meaning: '무', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '蕪', reading: 'かぶ', meaning: '순무', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '牛蒡', reading: 'ごぼう', meaning: '우엉', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '蓮根', reading: 'れんこん', meaning: '연근', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '玉葱', reading: 'たまねぎ', meaning: '양파', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '紫玉葱', reading: 'むらさきたまねぎ', meaning: '적양파', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: 'ジャガイモ', reading: 'ジャガイモ', meaning: '감자', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '薩摩芋', reading: 'さつまいも', meaning: '고구마', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '長芋', reading: 'ながいも', meaning: '마', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '山芋', reading: 'やまいも', meaning: '산마', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '里芋', reading: 'さといも', meaning: '토란', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: 'にんにく', reading: 'にんにく', meaning: '마늘', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: '生姜', reading: 'しょうが', meaning: '생강', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: 'みょうが', reading: 'みょうが', meaning: '양하', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: 'ラディッシュ', reading: 'ラディッシュ', meaning: '래디시', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: 'ビーツ', reading: 'ビーツ', meaning: '비트', tags: ['채소', '뿌리채소'], jlpt_level: null },
  { term: 'タロイモ', reading: 'タロイモ', meaning: '타로토란', tags: ['채소', '뿌리채소'], jlpt_level: null },

  // === 열매채소 (fruit-vegetables) ===
  { term: 'トマト', reading: 'トマト', meaning: '토마토', tags: ['채소', '열매채소'], jlpt_level: 5 },
  { term: 'ミニトマト', reading: 'ミニトマト', meaning: '방울토마토', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'きゅうり', reading: 'きゅうり', meaning: '오이', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: '茄子', reading: 'なす', meaning: '가지', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'ピーマン', reading: 'ピーマン', meaning: '피망', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'パプリカ', reading: 'パプリカ', meaning: '파프리카', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'ししとう', reading: 'ししとう', meaning: '꽈리고추', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: '唐辛子', reading: 'とうがらし', meaning: '고추', tags: ['채소', '향신료'], jlpt_level: null },
  { term: '青唐辛子', reading: 'あおとうがらし', meaning: '청고추', tags: ['채소', '향신료'], jlpt_level: null },
  { term: 'かぼちゃ', reading: 'かぼちゃ', meaning: '호박', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'ズッキーニ', reading: 'ズッキーニ', meaning: '주키니', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: '冬瓜', reading: 'とうがん', meaning: '동아', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'ゴーヤ', reading: 'ゴーヤ', meaning: '여주', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'オクラ', reading: 'オクラ', meaning: '오크라', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: 'とうもろこし', reading: 'とうもろこし', meaning: '옥수수', tags: ['채소', '열매채소', '곡물'], jlpt_level: null },
  { term: 'スイートコーン', reading: 'スイートコーン', meaning: '스위트콘', tags: ['채소', '열매채소'], jlpt_level: null },
  { term: '枝豆', reading: 'えだまめ', meaning: '풋콩', tags: ['채소', '콩류'], jlpt_level: null },
  { term: 'ブロッコリー', reading: 'ブロッコリー', meaning: '브로콜리', tags: ['채소'], jlpt_level: null },
  { term: 'カリフラワー', reading: 'カリフラワー', meaning: '콜리플라워', tags: ['채소'], jlpt_level: null },
  { term: 'アスパラガス', reading: 'アスパラガス', meaning: '아스파라거스', tags: ['채소'], jlpt_level: null },
  { term: 'セロリ', reading: 'セロリ', meaning: '셀러리', tags: ['채소'], jlpt_level: null },
  { term: 'ねぎ', reading: 'ねぎ', meaning: '파', tags: ['채소', '잎채소'], jlpt_level: null },
  { term: '玉蜀黍', reading: 'とうもろこし', meaning: '옥수수 (한자)', tags: ['채소', '곡물'], jlpt_level: null },
  { term: 'もやし', reading: 'もやし', meaning: '숙주나물', tags: ['채소'], jlpt_level: null },
  { term: '豆苗', reading: 'とうみょう', meaning: '두묘 (완두 새싹)', tags: ['채소'], jlpt_level: null },
  { term: 'スプラウト', reading: 'スプラウト', meaning: '새싹채소', tags: ['채소'], jlpt_level: null },
  { term: 'カイワレ大根', reading: 'カイワレだいこん', meaning: '무순', tags: ['채소'], jlpt_level: null },
  { term: 'たけのこ', reading: 'たけのこ', meaning: '죽순', tags: ['채소'], jlpt_level: null },
  { term: 'アーティチョーク', reading: 'アーティチョーク', meaning: '아티초크', tags: ['채소'], jlpt_level: null },
  { term: 'フェンネル', reading: 'フェンネル', meaning: '회향', tags: ['채소', '향신료'], jlpt_level: null },

  // === 과일 (fruits) ===
  { term: '林檎', reading: 'りんご', meaning: '사과', tags: ['과일'], jlpt_level: 5 },
  { term: '蜜柑', reading: 'みかん', meaning: '귤', tags: ['과일'], jlpt_level: null },
  { term: 'オレンジ', reading: 'オレンジ', meaning: '오렌지', tags: ['과일'], jlpt_level: null },
  { term: 'レモン', reading: 'レモン', meaning: '레몬', tags: ['과일'], jlpt_level: null },
  { term: 'ライム', reading: 'ライム', meaning: '라임', tags: ['과일'], jlpt_level: null },
  { term: 'グレープフルーツ', reading: 'グレープフルーツ', meaning: '자몽', tags: ['과일'], jlpt_level: null },
  { term: '柚子', reading: 'ゆず', meaning: '유자', tags: ['과일'], jlpt_level: null },
  { term: 'すだち', reading: 'すだち', meaning: '영귤', tags: ['과일'], jlpt_level: null },
  { term: 'かぼす', reading: 'かぼす', meaning: '카보스', tags: ['과일'], jlpt_level: null },
  { term: 'バナナ', reading: 'バナナ', meaning: '바나나', tags: ['과일'], jlpt_level: 5 },
  { term: '苺', reading: 'いちご', meaning: '딸기', tags: ['과일'], jlpt_level: null },
  { term: 'ブルーベリー', reading: 'ブルーベリー', meaning: '블루베리', tags: ['과일'], jlpt_level: null },
  { term: 'ラズベリー', reading: 'ラズベリー', meaning: '라즈베리', tags: ['과일'], jlpt_level: null },
  { term: 'クランベリー', reading: 'クランベリー', meaning: '크랜베리', tags: ['과일'], jlpt_level: null },
  { term: '葡萄', reading: 'ぶどう', meaning: '포도', tags: ['과일'], jlpt_level: null },
  { term: 'マスカット', reading: 'マスカット', meaning: '머스캣', tags: ['과일'], jlpt_level: null },
  { term: '巨峰', reading: 'きょほう', meaning: '거봉', tags: ['과일'], jlpt_level: null },
  { term: '桃', reading: 'もも', meaning: '복숭아', tags: ['과일'], jlpt_level: null },
  { term: '梅', reading: 'うめ', meaning: '매실', tags: ['과일'], jlpt_level: null },
  { term: '梨', reading: 'なし', meaning: '배', tags: ['과일'], jlpt_level: null },
  { term: '柿', reading: 'かき', meaning: '감', tags: ['과일'], jlpt_level: null },
  { term: '西瓜', reading: 'すいか', meaning: '수박', tags: ['과일'], jlpt_level: null },
  { term: 'メロン', reading: 'メロン', meaning: '멜론', tags: ['과일'], jlpt_level: null },
  { term: 'パイナップル', reading: 'パイナップル', meaning: '파인애플', tags: ['과일'], jlpt_level: null },
  { term: 'マンゴー', reading: 'マンゴー', meaning: '망고', tags: ['과일'], jlpt_level: null },
  { term: 'パパイヤ', reading: 'パパイヤ', meaning: '파파야', tags: ['과일'], jlpt_level: null },
  { term: 'キウイ', reading: 'キウイ', meaning: '키위', tags: ['과일'], jlpt_level: null },
  { term: 'アボカド', reading: 'アボカド', meaning: '아보카도', tags: ['과일'], jlpt_level: null },
  { term: 'ココナッツ', reading: 'ココナッツ', meaning: '코코넛', tags: ['과일'], jlpt_level: null },
  { term: '桜桃', reading: 'さくらんぼ', meaning: '체리', tags: ['과일'], jlpt_level: null },
  { term: '杏', reading: 'あんず', meaning: '살구', tags: ['과일'], jlpt_level: null },
  { term: 'プルーン', reading: 'プルーン', meaning: '프룬, 자두', tags: ['과일'], jlpt_level: null },
  { term: '李', reading: 'すもも', meaning: '자두', tags: ['과일'], jlpt_level: null },
  { term: 'いちじく', reading: 'いちじく', meaning: '무화과', tags: ['과일'], jlpt_level: null },
  { term: '柘榴', reading: 'ざくろ', meaning: '석류', tags: ['과일'], jlpt_level: null },
  { term: 'ドラゴンフルーツ', reading: 'ドラゴンフルーツ', meaning: '용과', tags: ['과일'], jlpt_level: null },
  { term: 'ライチ', reading: 'ライチ', meaning: '리치', tags: ['과일'], jlpt_level: null },
  { term: 'パッションフルーツ', reading: 'パッションフルーツ', meaning: '패션프루트', tags: ['과일'], jlpt_level: null },
  { term: '栗', reading: 'くり', meaning: '밤', tags: ['과일'], jlpt_level: null },
  { term: 'ナツメ', reading: 'ナツメ', meaning: '대추', tags: ['과일'], jlpt_level: null },

  // === 육류 (meat) ===
  { term: '牛肉', reading: 'ぎゅうにく', meaning: '소고기', tags: ['육류'], jlpt_level: 4 },
  { term: '豚肉', reading: 'ぶたにく', meaning: '돼지고기', tags: ['육류'], jlpt_level: 4 },
  { term: '鶏肉', reading: 'とりにく', meaning: '닭고기', tags: ['육류'], jlpt_level: 4 },
  { term: '羊肉', reading: 'ようにく', meaning: '양고기', tags: ['육류'], jlpt_level: null },
  { term: 'ラム肉', reading: 'ラムにく', meaning: '램, 어린양고기', tags: ['육류'], jlpt_level: null },
  { term: '馬肉', reading: 'ばにく', meaning: '말고기', tags: ['육류'], jlpt_level: null },
  { term: '鴨肉', reading: 'かもにく', meaning: '오리고기', tags: ['육류'], jlpt_level: null },
  { term: '七面鳥', reading: 'しちめんちょう', meaning: '칠면조', tags: ['육류'], jlpt_level: null },
  { term: '挽肉', reading: 'ひきにく', meaning: '다진 고기', tags: ['육류'], jlpt_level: null },
  { term: '合挽肉', reading: 'あいびきにく', meaning: '소돼지 혼합 다짐육', tags: ['육류'], jlpt_level: null },
  { term: 'ロース', reading: 'ロース', meaning: '등심', tags: ['육류'], jlpt_level: null },
  { term: 'バラ肉', reading: 'バラにく', meaning: '삼겹살, 양지', tags: ['육류'], jlpt_level: null },
  { term: 'もも肉', reading: 'ももにく', meaning: '다리살', tags: ['육류'], jlpt_level: null },
  { term: '胸肉', reading: 'むねにく', meaning: '가슴살', tags: ['육류'], jlpt_level: null },
  { term: 'ささみ', reading: 'ささみ', meaning: '닭안심', tags: ['육류'], jlpt_level: null },
  { term: '手羽先', reading: 'てばさき', meaning: '닭날개', tags: ['육류'], jlpt_level: null },
  { term: '手羽元', reading: 'てばもと', meaning: '닭봉', tags: ['육류'], jlpt_level: null },
  { term: 'モツ', reading: 'モツ', meaning: '내장', tags: ['육류'], jlpt_level: null },
  { term: 'レバー', reading: 'レバー', meaning: '간', tags: ['육류'], jlpt_level: null },
  { term: '心臓', reading: 'しんぞう', meaning: '심장', tags: ['육류'], jlpt_level: null },
  { term: 'タン', reading: 'タン', meaning: '혀', tags: ['육류'], jlpt_level: null },
  { term: 'ホルモン', reading: 'ホルモン', meaning: '곱창', tags: ['육류'], jlpt_level: null },
  { term: 'ベーコン', reading: 'ベーコン', meaning: '베이컨', tags: ['육류', '가공식품'], jlpt_level: null },
  { term: 'ハム', reading: 'ハム', meaning: '햄', tags: ['육류', '가공식품'], jlpt_level: null },
  { term: 'ソーセージ', reading: 'ソーセージ', meaning: '소시지', tags: ['육류', '가공식품'], jlpt_level: null },
  { term: 'ウインナー', reading: 'ウインナー', meaning: '비엔나소시지', tags: ['육류', '가공식품'], jlpt_level: null },
  { term: 'サラミ', reading: 'サラミ', meaning: '살라미', tags: ['육류', '가공식품'], jlpt_level: null },
  { term: 'ステーキ肉', reading: 'ステーキにく', meaning: '스테이크용 고기', tags: ['육류'], jlpt_level: null },
  { term: '霜降り', reading: 'しもふり', meaning: '마블링', tags: ['육류'], jlpt_level: null },
  { term: '和牛', reading: 'わぎゅう', meaning: '와규', tags: ['육류'], jlpt_level: null },

  // === 곡물 (grains) ===
  { term: '米', reading: 'こめ', meaning: '쌀', tags: ['곡물'], jlpt_level: 5 },
  { term: '玄米', reading: 'げんまい', meaning: '현미', tags: ['곡물'], jlpt_level: null },
  { term: '白米', reading: 'はくまい', meaning: '백미', tags: ['곡물'], jlpt_level: null },
  { term: 'もち米', reading: 'もちごめ', meaning: '찹쌀', tags: ['곡물'], jlpt_level: null },
  { term: '小麦', reading: 'こむぎ', meaning: '밀', tags: ['곡물'], jlpt_level: null },
  { term: '小麦粉', reading: 'こむぎこ', meaning: '밀가루', tags: ['곡물'], jlpt_level: null },
  { term: '強力粉', reading: 'きょうりきこ', meaning: '강력분', tags: ['곡물'], jlpt_level: null },
  { term: '薄力粉', reading: 'はくりきこ', meaning: '박력분', tags: ['곡물'], jlpt_level: null },
  { term: 'パン粉', reading: 'パンこ', meaning: '빵가루', tags: ['곡물'], jlpt_level: null },
  { term: '蕎麦粉', reading: 'そばこ', meaning: '메밀가루', tags: ['곡물'], jlpt_level: null },
  { term: '片栗粉', reading: 'かたくりこ', meaning: '녹말가루 (감자전분)', tags: ['곡물'], jlpt_level: null },
  { term: 'コーンスターチ', reading: 'コーンスターチ', meaning: '옥수수전분', tags: ['곡물'], jlpt_level: null },
  { term: '大麦', reading: 'おおむぎ', meaning: '보리', tags: ['곡물'], jlpt_level: null },
  { term: '麦', reading: 'むぎ', meaning: '보리, 밀류', tags: ['곡물'], jlpt_level: null },
  { term: '燕麦', reading: 'えんばく', meaning: '귀리', tags: ['곡물'], jlpt_level: null },
  { term: 'オートミール', reading: 'オートミール', meaning: '오트밀', tags: ['곡물'], jlpt_level: null },
  { term: '蕎麦', reading: 'そば', meaning: '메밀', tags: ['곡물', '면류'], jlpt_level: null },
  { term: '粟', reading: 'あわ', meaning: '조', tags: ['곡물'], jlpt_level: null },

  // === 콩류 (legumes) ===
  { term: '大豆', reading: 'だいず', meaning: '대두', tags: ['콩류'], jlpt_level: null },
  { term: '黒豆', reading: 'くろまめ', meaning: '검은콩', tags: ['콩류'], jlpt_level: null },
  { term: '小豆', reading: 'あずき', meaning: '팥', tags: ['콩류'], jlpt_level: null },
  { term: '緑豆', reading: 'りょくとう', meaning: '녹두', tags: ['콩류'], jlpt_level: null },
  { term: 'うずら豆', reading: 'うずらまめ', meaning: '강낭콩 (얼룩)', tags: ['콩류'], jlpt_level: null },
  { term: 'いんげん豆', reading: 'いんげんまめ', meaning: '강낭콩', tags: ['콩류'], jlpt_level: null },
  { term: 'えんどう豆', reading: 'えんどうまめ', meaning: '완두콩', tags: ['콩류'], jlpt_level: null },
  { term: 'そら豆', reading: 'そらまめ', meaning: '잠두', tags: ['콩류'], jlpt_level: null },
  { term: 'レンズ豆', reading: 'レンズまめ', meaning: '렌즈콩', tags: ['콩류'], jlpt_level: null },
  { term: 'ひよこ豆', reading: 'ひよこまめ', meaning: '병아리콩', tags: ['콩류'], jlpt_level: null },
  { term: '豆腐', reading: 'とうふ', meaning: '두부', tags: ['콩류', '가공식품'], jlpt_level: null },
  { term: '絹豆腐', reading: 'きぬどうふ', meaning: '연두부', tags: ['콩류', '가공식품'], jlpt_level: null },
  { term: '木綿豆腐', reading: 'もめんどうふ', meaning: '단단한 두부', tags: ['콩류', '가공식품'], jlpt_level: null },
  { term: '油揚げ', reading: 'あぶらあげ', meaning: '유부', tags: ['콩류', '가공식품'], jlpt_level: null },
  { term: '厚揚げ', reading: 'あつあげ', meaning: '두꺼운 유부', tags: ['콩류', '가공식품'], jlpt_level: null },

  // === 버섯 (mushrooms, excluding なめこ) ===
  { term: '椎茸', reading: 'しいたけ', meaning: '표고버섯', tags: ['버섯'], jlpt_level: null },
  { term: '舞茸', reading: 'まいたけ', meaning: '잎새버섯', tags: ['버섯'], jlpt_level: null },
  { term: 'エリンギ', reading: 'エリンギ', meaning: '새송이버섯', tags: ['버섯'], jlpt_level: null },
  { term: 'えのき茸', reading: 'えのきたけ', meaning: '팽이버섯', tags: ['버섯'], jlpt_level: null },
  { term: 'しめじ', reading: 'しめじ', meaning: '만가닥버섯', tags: ['버섯'], jlpt_level: null },
  { term: 'マッシュルーム', reading: 'マッシュルーム', meaning: '양송이버섯', tags: ['버섯'], jlpt_level: null },
  { term: 'トリュフ', reading: 'トリュフ', meaning: '트러플', tags: ['버섯'], jlpt_level: null },
  { term: '松茸', reading: 'まつたけ', meaning: '송이버섯', tags: ['버섯'], jlpt_level: null },
  { term: 'きくらげ', reading: 'きくらげ', meaning: '목이버섯', tags: ['버섯'], jlpt_level: null },
  { term: '白きくらげ', reading: 'しろきくらげ', meaning: '흰목이', tags: ['버섯'], jlpt_level: null },
  { term: 'ポルチーニ', reading: 'ポルチーニ', meaning: '포르치니', tags: ['버섯'], jlpt_level: null },
  { term: 'ヒラタケ', reading: 'ヒラタケ', meaning: '느타리버섯', tags: ['버섯'], jlpt_level: null },

  // === 해조류 (seaweed) ===
  { term: 'ひじき', reading: 'ひじき', meaning: '톳', tags: ['해조류'], jlpt_level: null },
  { term: 'もずく', reading: 'もずく', meaning: '큰실말', tags: ['해조류'], jlpt_level: null },
  { term: '寒天', reading: 'かんてん', meaning: '한천', tags: ['해조류', '가공식품'], jlpt_level: null },
  { term: '青のり', reading: 'あおのり', meaning: '파래', tags: ['해조류'], jlpt_level: null },
  { term: '焼き海苔', reading: 'やきのり', meaning: '구운 김', tags: ['해조류', '가공식품'], jlpt_level: null },
  { term: '味付け海苔', reading: 'あじつけのり', meaning: '조미김', tags: ['해조류', '가공식품'], jlpt_level: null },
  { term: 'とろろ昆布', reading: 'とろろこんぶ', meaning: '실 다시마', tags: ['해조류', '가공식품'], jlpt_level: null },
  { term: '塩昆布', reading: 'しおこんぶ', meaning: '소금 다시마', tags: ['해조류', '가공식품'], jlpt_level: null },

  // === 향신료/허브 (spices/herbs) ===
  { term: '胡椒', reading: 'こしょう', meaning: '후추', tags: ['향신료'], jlpt_level: null },
  { term: '黒胡椒', reading: 'くろこしょう', meaning: '흑후추', tags: ['향신료'], jlpt_level: null },
  { term: '白胡椒', reading: 'しろこしょう', meaning: '백후추', tags: ['향신료'], jlpt_level: null },
  { term: '山椒', reading: 'さんしょう', meaning: '산초', tags: ['향신료'], jlpt_level: null },
  { term: '七味唐辛子', reading: 'しちみとうがらし', meaning: '시치미', tags: ['향신료'], jlpt_level: null },
  { term: '一味唐辛子', reading: 'いちみとうがらし', meaning: '고춧가루', tags: ['향신료'], jlpt_level: null },
  { term: 'ナツメグ', reading: 'ナツメグ', meaning: '넛맥', tags: ['향신료'], jlpt_level: null },
  { term: 'シナモン', reading: 'シナモン', meaning: '계피', tags: ['향신료'], jlpt_level: null },
  { term: 'クローブ', reading: 'クローブ', meaning: '정향', tags: ['향신료'], jlpt_level: null },
  { term: 'カルダモン', reading: 'カルダモン', meaning: '카르다몸', tags: ['향신료'], jlpt_level: null },
  { term: 'コリアンダー', reading: 'コリアンダー', meaning: '고수, 코리앤더', tags: ['향신료'], jlpt_level: null },
  { term: 'パクチー', reading: 'パクチー', meaning: '고수 (잎)', tags: ['향신료'], jlpt_level: null },
  { term: 'クミン', reading: 'クミン', meaning: '쿠민', tags: ['향신료'], jlpt_level: null },
  { term: 'ターメリック', reading: 'ターメリック', meaning: '강황', tags: ['향신료'], jlpt_level: null },
  { term: 'サフラン', reading: 'サフラン', meaning: '사프란', tags: ['향신료'], jlpt_level: null },
  { term: 'ローズマリー', reading: 'ローズマリー', meaning: '로즈마리', tags: ['향신료'], jlpt_level: null },
  { term: 'タイム', reading: 'タイム', meaning: '타임', tags: ['향신료'], jlpt_level: null },
  { term: 'オレガノ', reading: 'オレガノ', meaning: '오레가노', tags: ['향신료'], jlpt_level: null },

  // === 조미료 (seasonings) ===
  { term: '塩', reading: 'しお', meaning: '소금', tags: ['조미료'], jlpt_level: 5 },
  { term: '砂糖', reading: 'さとう', meaning: '설탕', tags: ['조미료'], jlpt_level: 5 },
  { term: '黒砂糖', reading: 'くろざとう', meaning: '흑설탕', tags: ['조미료'], jlpt_level: null },
  { term: 'グラニュー糖', reading: 'グラニューとう', meaning: '그래뉴당', tags: ['조미료'], jlpt_level: null },
  { term: '蜂蜜', reading: 'はちみつ', meaning: '꿀', tags: ['조미료'], jlpt_level: null },
  { term: 'メープルシロップ', reading: 'メープルシロップ', meaning: '메이플시럽', tags: ['조미료'], jlpt_level: null },
  { term: '醤油', reading: 'しょうゆ', meaning: '간장', tags: ['조미료'], jlpt_level: 4 },
  { term: '濃口醤油', reading: 'こいくちしょうゆ', meaning: '진간장', tags: ['조미료'], jlpt_level: null },
  { term: '薄口醤油', reading: 'うすくちしょうゆ', meaning: '연한 간장', tags: ['조미료'], jlpt_level: null },
  { term: 'たまり醤油', reading: 'たまりしょうゆ', meaning: '진한 다마리 간장', tags: ['조미료'], jlpt_level: null },
  { term: '味噌', reading: 'みそ', meaning: '된장 (미소)', tags: ['조미료'], jlpt_level: 4 },
  { term: '赤味噌', reading: 'あかみそ', meaning: '적된장', tags: ['조미료'], jlpt_level: null },
  { term: '白味噌', reading: 'しろみそ', meaning: '백된장', tags: ['조미료'], jlpt_level: null },
  { term: '酢', reading: 'す', meaning: '식초', tags: ['조미료'], jlpt_level: null },
  { term: '米酢', reading: 'こめず', meaning: '쌀식초', tags: ['조미료'], jlpt_level: null },
  { term: '黒酢', reading: 'くろず', meaning: '흑초', tags: ['조미료'], jlpt_level: null },
  { term: 'バルサミコ酢', reading: 'バルサミコす', meaning: '발사믹 식초', tags: ['조미료'], jlpt_level: null },
  { term: 'みりん', reading: 'みりん', meaning: '미림', tags: ['조미료'], jlpt_level: null },
  { term: '料理酒', reading: 'りょうりしゅ', meaning: '맛술', tags: ['조미료'], jlpt_level: null },
  { term: '出汁', reading: 'だし', meaning: '다시 (육수)', tags: ['조미료'], jlpt_level: null },
  { term: 'めんつゆ', reading: 'めんつゆ', meaning: '면 쯔유', tags: ['조미료'], jlpt_level: null },
  { term: 'ポン酢', reading: 'ポンず', meaning: '폰즈', tags: ['조미료'], jlpt_level: null },
  { term: 'マヨネーズ', reading: 'マヨネーズ', meaning: '마요네즈', tags: ['조미료'], jlpt_level: null },
  { term: 'ケチャップ', reading: 'ケチャップ', meaning: '케찹', tags: ['조미료'], jlpt_level: null },
  { term: 'ウスターソース', reading: 'ウスターソース', meaning: '우스터소스', tags: ['조미료'], jlpt_level: null },
  { term: 'お好み焼きソース', reading: 'おこのみやきソース', meaning: '오코노미야키소스', tags: ['조미료'], jlpt_level: null },
  { term: '豆板醤', reading: 'トウバンジャン', meaning: '두반장', tags: ['조미료'], jlpt_level: null },
  { term: '甜麺醤', reading: 'テンメンジャン', meaning: '첨면장', tags: ['조미료'], jlpt_level: null },
  { term: 'オイスターソース', reading: 'オイスターソース', meaning: '굴소스', tags: ['조미료'], jlpt_level: null },
  { term: 'ナンプラー', reading: 'ナンプラー', meaning: '남플라 (액젓)', tags: ['조미료'], jlpt_level: null },
  { term: 'コチュジャン', reading: 'コチュジャン', meaning: '고추장', tags: ['조미료'], jlpt_level: null },
  { term: 'ごま油', reading: 'ごまあぶら', meaning: '참기름', tags: ['조미료', '유지류'], jlpt_level: null },
  { term: 'ラー油', reading: 'ラーゆ', meaning: '고추기름', tags: ['조미료', '유지류'], jlpt_level: null },
  { term: '味の素', reading: 'あじのもと', meaning: '아지노모토 (MSG)', tags: ['조미료'], jlpt_level: null },
  { term: '顆粒だし', reading: 'かりゅうだし', meaning: '과립 다시', tags: ['조미료'], jlpt_level: null },

  // === 유제품 (dairy) ===
  { term: '牛乳', reading: 'ぎゅうにゅう', meaning: '우유', tags: ['유제품'], jlpt_level: 5 },
  { term: '低脂肪乳', reading: 'ていしぼうにゅう', meaning: '저지방 우유', tags: ['유제품'], jlpt_level: null },
  { term: '豆乳', reading: 'とうにゅう', meaning: '두유', tags: ['유제품', '콩류'], jlpt_level: null },
  { term: '生クリーム', reading: 'なまクリーム', meaning: '생크림', tags: ['유제품'], jlpt_level: null },
  { term: 'バター', reading: 'バター', meaning: '버터', tags: ['유제품'], jlpt_level: 5 },
  { term: '無塩バター', reading: 'むえんバター', meaning: '무염버터', tags: ['유제품'], jlpt_level: null },
  { term: 'チーズ', reading: 'チーズ', meaning: '치즈', tags: ['유제품'], jlpt_level: 5 },
  { term: 'モッツァレラ', reading: 'モッツァレラ', meaning: '모짜렐라', tags: ['유제품'], jlpt_level: null },
  { term: 'パルメザン', reading: 'パルメザン', meaning: '파마산', tags: ['유제품'], jlpt_level: null },
  { term: 'クリームチーズ', reading: 'クリームチーズ', meaning: '크림치즈', tags: ['유제품'], jlpt_level: null },
  { term: 'ヨーグルト', reading: 'ヨーグルト', meaning: '요거트', tags: ['유제품'], jlpt_level: null },
  { term: '練乳', reading: 'れんにゅう', meaning: '연유', tags: ['유제품'], jlpt_level: null },

  // === 달걀 (eggs) ===
  { term: '卵', reading: 'たまご', meaning: '계란', tags: ['달걀'], jlpt_level: 5 },
  { term: '鶏卵', reading: 'けいらん', meaning: '닭알', tags: ['달걀'], jlpt_level: null },
  { term: 'うずらの卵', reading: 'うずらのたまご', meaning: '메추리알', tags: ['달걀'], jlpt_level: null },
  { term: '卵白', reading: 'らんぱく', meaning: '흰자', tags: ['달걀'], jlpt_level: null },
  { term: '卵黄', reading: 'らんおう', meaning: '노른자', tags: ['달걀'], jlpt_level: null },

  // === 면류 (noodles) ===
  { term: 'うどん', reading: 'うどん', meaning: '우동', tags: ['면류'], jlpt_level: null },
  { term: 'ラーメン', reading: 'ラーメン', meaning: '라멘', tags: ['면류'], jlpt_level: 5 },
  { term: 'そうめん', reading: 'そうめん', meaning: '소면', tags: ['면류'], jlpt_level: null },
  { term: '冷麦', reading: 'ひやむぎ', meaning: '히야무기', tags: ['면류'], jlpt_level: null },
  { term: 'きしめん', reading: 'きしめん', meaning: '기시멘', tags: ['면류'], jlpt_level: null },
  { term: '中華麺', reading: 'ちゅうかめん', meaning: '중화면', tags: ['면류'], jlpt_level: null },
  { term: 'パスタ', reading: 'パスタ', meaning: '파스타', tags: ['면류'], jlpt_level: null },
  { term: 'スパゲッティ', reading: 'スパゲッティ', meaning: '스파게티', tags: ['면류'], jlpt_level: null },
  { term: 'ペンネ', reading: 'ペンネ', meaning: '펜네', tags: ['면류'], jlpt_level: null },
  { term: 'マカロニ', reading: 'マカロニ', meaning: '마카로니', tags: ['면류'], jlpt_level: null },
  { term: 'ラザニア', reading: 'ラザニア', meaning: '라자냐', tags: ['면류'], jlpt_level: null },
  { term: 'フォー', reading: 'フォー', meaning: '베트남쌀국수', tags: ['면류'], jlpt_level: null },
  { term: '春雨', reading: 'はるさめ', meaning: '당면', tags: ['면류'], jlpt_level: null },
  { term: 'ビーフン', reading: 'ビーフン', meaning: '쌀국수', tags: ['면류'], jlpt_level: null },
  { term: '焼きそば麺', reading: 'やきそばめん', meaning: '야끼소바 면', tags: ['면류'], jlpt_level: null },

  // === 가공식품 (processed) ===
  { term: '納豆', reading: 'なっとう', meaning: '낫토', tags: ['가공식품', '콩류'], jlpt_level: null },
  { term: 'こんにゃく', reading: 'こんにゃく', meaning: '곤약', tags: ['가공식품'], jlpt_level: null },
  { term: 'しらたき', reading: 'しらたき', meaning: '실곤약', tags: ['가공식품'], jlpt_level: null },
  { term: '高野豆腐', reading: 'こうやどうふ', meaning: '동결건조 두부', tags: ['가공식품', '콩류'], jlpt_level: null },
  { term: 'がんもどき', reading: 'がんもどき', meaning: '간모도키 (두부완자)', tags: ['가공식품'], jlpt_level: null },
  { term: '漬物', reading: 'つけもの', meaning: '쯔케모노 (절임)', tags: ['가공식품'], jlpt_level: null },
  { term: '梅干し', reading: 'うめぼし', meaning: '우메보시 (매실절임)', tags: ['가공식품'], jlpt_level: null },
  { term: '沢庵', reading: 'たくあん', meaning: '다쿠앙 (단무지)', tags: ['가공식품'], jlpt_level: null },
  { term: 'キムチ', reading: 'キムチ', meaning: '김치', tags: ['가공식품'], jlpt_level: null },
  { term: '糠漬け', reading: 'ぬかづけ', meaning: '쌀겨절임', tags: ['가공식품'], jlpt_level: null },
  { term: '生麩', reading: 'なまふ', meaning: '나마후 (밀글루텐)', tags: ['가공식품'], jlpt_level: null },
  { term: '麩', reading: 'ふ', meaning: '후 (밀글루텐 건조품)', tags: ['가공식품'], jlpt_level: null },
  { term: 'カレールー', reading: 'カレールー', meaning: '카레 루', tags: ['가공식품'], jlpt_level: null },
  { term: 'シチュールー', reading: 'シチュールー', meaning: '스튜 루', tags: ['가공식품'], jlpt_level: null },
  { term: 'ふりかけ', reading: 'ふりかけ', meaning: '후리카케', tags: ['가공식품'], jlpt_level: null },
  { term: 'お茶漬けの素', reading: 'おちゃづけのもと', meaning: '오차즈케 양념', tags: ['가공식품'], jlpt_level: null },

  // === 유지류 (oils/fats) ===
  { term: 'サラダ油', reading: 'サラダゆ', meaning: '식용유', tags: ['유지류'], jlpt_level: null },
  { term: 'オリーブオイル', reading: 'オリーブオイル', meaning: '올리브유', tags: ['유지류'], jlpt_level: null },
  { term: 'えごま油', reading: 'えごまあぶら', meaning: '들기름', tags: ['유지류'], jlpt_level: null },
  { term: '菜種油', reading: 'なたねあぶら', meaning: '카놀라유, 유채유', tags: ['유지류'], jlpt_level: null },
  { term: '米油', reading: 'こめあぶら', meaning: '현미유', tags: ['유지류'], jlpt_level: null },
  { term: 'ココナッツオイル', reading: 'ココナッツオイル', meaning: '코코넛오일', tags: ['유지류'], jlpt_level: null },
  { term: 'ラード', reading: 'ラード', meaning: '라드', tags: ['유지류'], jlpt_level: null },
  { term: 'ヘット', reading: 'ヘット', meaning: '쇠기름', tags: ['유지류'], jlpt_level: null },
];
